vich_uploader:
    db_driver: orm

    mappings:
        cars:
            uri_prefix: build/upload/images/voitures
            upload_destination: '%kernel.project_dir%/public/build/upload/images/voitures'
            # namer: Vich\UploaderBundle\Naming\UniqidNamer
